### ISSUE TITLE
Google calendar config

### ISSUE THREAD

**Issue by rikki78** [naimo84/node-red-contrib-ical-events#32]
**Describe the bug**
I'm trying to configure the node to fetch google calendar but it is not clear what to fill in where

**To Reproduce**
I'm using the caldav option

Do I need the google user name?
The ClientID?
Cleint secret?

Note this is not a bug, I just need help ;)

**Comment by rikki78** [comment]
I think I found the setup, now I get this error
```
Error parsing response Error: Unexpected close tag
Line: 0
Column: 1843
Char: >
    at error (/config/node-red/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/config/node-red/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/config/node-red/node_modules/sax/lib/sax.js:871:9)
    at SAXParser.write (/config/node-red/node_modules/sax/lib/sax.js:1436:13)
    at module.exports (/config/node-red/node_modules/xml-js/lib/xml2js.js:346:12)
    at Object.module.exports [as xml2json] (/config/node-red/node_modules/xml-js/lib/xml2json.js:13:8)
    at ClientRequest.<anonymous> (/config/node-red/node_modules/node-red-contrib-ical-events/src/icloud.ts:72:51)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketCloseListener (_http_client.js:374:9)
    at TLSSocket.emit (events.js:228:7)
    at net.js:664:12
    at TCP.done (_tls_wrap.js:481:7) {
  note: [Circular]
}
````

**Comment by naimo84** [comment]
Hey Rikki,

what nodejs Version, node-red version are you using? "Unexpected close tag" sounds like a syntax.

Greets,
Benjamin

**Comment by rikki78** [comment]
You are right I was using the wrong type 😄 
Thanks!
