### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by geertvercamer** [naimo84/node-red-contrib-ical-events#56]
Getting this error on the start of an event in the trigger node

**To Reproduce**
1. trigger node
2. ical url of calendar with event starting at ie. 09.27
3. at start time:
16 Jul 09:27:00 - [red] Uncaught Exception:
16 Jul 09:27:00 - TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at cronJobEnd (/home/geert/.node-red/node_modules/node-red-contrib-ical-events/dist/ical-events.js:313:33)
    at CronJob.fireOnTick (/home/geert/.node-red/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/home/geert/.node-red/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)

**node-red-contrib-ical-events**
 - 0.16.0
 - node-red version 1.1.2
 - nodejs version 14.5.0

**Comment by naimo84** [comment]
I'm so sorry for the circumstances...

Should be fixed with v0.17. It's already on the way

**Comment by geertvercamer** [comment]
yep, fixed.
Thanks!!!
