### ISSUE TITLE
Crash with uncaught exception

### ISSUE THREAD

**Issue by Skyr** [naimo84/node-red-contrib-ical-events#59]
**Describe the bug**

Tried to import my calendar from my Nextcloud instance via public ical link (unsuccessful, resulted just in an empty list). So I tried configuring the caldav access. Now nodered won't start up anymore due to an uncaught exception:

```
Jul 30 21:28:30 myhost Node-RED[20486]: 30 Jul 21:28:30 - [red] Uncaught Exception:
Jul 30 21:28:30 myhost Node-RED[20486]: 30 Jul 21:28:30 - ReferenceError: URL is not defined
Jul 30 21:28:30 myhost Node-RED[20486]:     at Object.CalDav (/var/lib/node-red/node_modules/node-red-contrib-ical-events/dist/caldav.js:79:15)
Jul 30 21:28:30 myhost Node-RED[20486]:     at getEvents (/var/lib/node-red/node_modules/node-red-contrib-ical-events/dist/helper.js:226:18)
Jul 30 21:28:30 myhost Node-RED[20486]:     at Object.getICal (/var/lib/node-red/node_modules/node-red-contrib-ical-events/dist/helper.js:21:9)
Jul 30 21:28:30 myhost Node-RED[20486]:     at cronCheckJob (/var/lib/node-red/node_modules/node-red-contrib-ical-events/dist/ical-sensor.js:136:18)
Jul 30 21:28:30 myhost Node-RED[20486]:     at CronJob.fireOnTick (/var/lib/node-red/node_modules/cron/lib/cron.js:600:23)
Jul 30 21:28:30 myhost Node-RED[20486]:     at Timeout.callbackWrapper [as _onTimeout] (/var/lib/node-red/node_modules/cron/lib/cron.js:667:10)
Jul 30 21:28:30 myhost Node-RED[20486]:     at ontimeout (timers.js:475:11)
Jul 30 21:28:30 myhost Node-RED[20486]:     at tryOnTimeout (timers.js:310:5)
Jul 30 21:28:30 myhost Node-RED[20486]:     at Timer.listOnTimeout (timers.js:270:5)
```

**node-red-contrib-ical-events**
 - Version 0.17.1
 - node-red 1.0.3 and 1.1.2
 - nodejs 8.9.4 and 8.17.0

**Comment by Skyr** [comment]
I'm a JS n00b, but I think adding

```
const { URL } = require('url');
```

to the require statements fixed the issue...
